### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by Dark32** [Dark32/RPchat2#36]
Я просто написал /rpchat и тут понеслось:

``` java
2014-03-13 00:18:23 [INFO] 222 issued server command: /rpchat
2014-03-13 00:18:23 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing 'rpchat' in org.bukkit.command.PluginCommand(rpchat, rpChat v2.2.0)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:196)
at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:548)
at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1351)
at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1217)
at org.bukkit.craftbukkit.v1_6_R2.entity.CraftPlayer.chat(CraftPlayer.java:242)
at ru.dark32.chat.CommandPreprocessListener.tabComplete(CommandPreprocessListener.java:32)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:452)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1332)
at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1217)
at org.bukkit.craftbukkit.v1_6_R2.entity.CraftPlayer.chat(CraftPlayer.java:242)
at ru.dark32.chat.CommandPreprocessListener.tabComplete(CommandPreprocessListener.java:32)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:452)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1332)
at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1217)
at org.bukkit.craftbukkit.v1_6_R2.entity.CraftPlayer.chat(CraftPlayer.java:242)
at ru.dark32.chat.CommandPreprocessListener.tabComplete(CommandPreprocessListener.java:32)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:452)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1332)
at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1217)
at org.bukkit.craftbukkit.v1_6_R2.entity.CraftPlayer.chat(CraftPlayer.java:242)
at ru.dark32.chat.CommandPreprocessListener.tabComplete(CommandPreprocessListener.java:32)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
...
```

И т.д.
Ввёл /s и тут:
(Раскрыть) Спойлер

``` java
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:29 [INFO] 222 issued server command: /s
2014-03-13 00:18:38 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
2014-03-13 00:18:43 [INFO] Unknown command. Type "help" for help.
```

/help:

``` java
2014-03-13 00:24:27 [INFO] 222 issued server command: /help
2014-03-13 00:24:27 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing 'help' in org.bukkit.command.defaults.HelpCommand(help)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:196)
at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:548)
at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1351)
at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1217)
at org.bukkit.craftbukkit.v1_6_R2.entity.CraftPlayer.chat(CraftPlayer.java:242)
at ru.dark32.chat.CommandPreprocessListener.tabComplete(CommandPreprocessListener.java:32)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
...
```

Думаю, что суть флуда понятна
Что-либо проверить в таких условиях, увы, не вышло.
Тестировалось на MCPC+ 1.6.2 last build

**Comment by Dark32** [comment]
Временная заглушка. Выпустил код не для релиза
